/*
 ** List of all the labels are being used in the app
 */
export const LABELS = {
  listIsEmpty: 'List is empty',
  no: 'No',
  search: 'search',
  appName: 'Stock APP',
  yes: 'Yes',
  beta: 'Beta',
  profit: 'Profit Margin',
  dividend: 'Dividend Yield',
  currentPrice: 'Current Price:',
  cancel: 'Cancel',
  ratio: 'P/E Ratio',
   marketCap: 'Market Cap',
  sector: 'Sector:',
  industry: 'Industry:',
  weekHigh: '52 Week-High ',
  weekLow: '52 Week-Low ',
  detailScreen: 'Detail Screen',
  selectDate: 'Select Date',
  didRecvCode: "Didn't receive code?",
  contact: 'Contact',
  contactLable: 'Fill in your phone number and location',
  phoneNumber: 'Phone Number',
  state: 'State',
  Country: 'Country',
  home: 'Home',
  profile: 'Profile',
  login: 'Login',
  continuenWithFacebook: 'Continue with Facebook',
  continuenWithGoogle: 'Continue with Google',
  continuenWithApple: 'Continue with Apple',
  continuenWithEmail: 'Continue with Email',
  signUp: 'Sign Up',
  algoace: 'Algoace',
  submit: 'Submit',
  welcomeBack: 'Welcome Back',
  selectCriteria: 'Select your criteria',
  signInLabel: 'Fill out your email address and password',
  tapToProceed: 'Tap to proceed',
  email: 'Email',
  forgotPasswordsmall: 'Forgot password?',
  resendCode: 'Resend code',
  password: 'Password',
  signUpLabel: 'Fill in your personal information',
  firstName: 'First Name',
  lastName: 'Last Name',
  emailAddress: 'Email Address',
  continue: 'Continue',
  dob: 'Date of birth',
  forgotPasswordBold: 'Forgot password',
  forgotChangePasswordLable:
    'Forgot password, please reset password, and confirm code via email.',
  forgotPasswordLable:
    'We understand you forgot your password, can you please provide your sign up email',
  resetPassword: 'Reset Password',
  re_enterPassword: 'Re-enter new password',
  confirmationCode: 'Confirmation code',
  confirmSignUp: 'Confirm Sign Up',
  verificationSentCode: 'Verification code has been sent to your email address',
  oops: 'Oops!',
  errorBoundaryLable: 'Something went wrong try again later',
  tryAgain: 'Try again',
};
